CREATE TABLE `usuarios` (
`ID` INT NOT NULL AUTO_INCREMENT,
`NOMBRE` VARCHAR(50) NOT NULL,
`APELLIDO`VARCHAR(50) NOT NULL,
`CLAVE` VARCHAR(50) NOT NULL,
`EMAIL` VARCHAR(50) NOT NULL,
PRIMARY KEY (`ID`));

ALTER TABLE `usuarios`
ADD CONSTRAINT CT_UQ_EMAIL
UNIQUE(`EMAIL`);